matrix:
  include:
    - os: linux
      language: python
      python: "3"
      install: "pip install -r pip-requirements.txt"
      # both of these cheat the fact that travis doesn't have multi-language support, but there aren't that many python libraries that lint json properly
      before_script:
        - npm install jsonlint -g
      script:
        - python forage-py3.py
        - python forage-py3.py -w csv
        - python forage-py3.py -w json
        - jsonlint output-hydrometric.json
    - os: linux
      language: python
      python: "2.7"
      install: "pip install -r pip-requirements.txt"
      # both of these cheat the fact that travis doesn't have multi-language support, but there aren't that many python libraries that lint json properly
      before_script:
        - npm install jsonlint -g
      script:
        - python forage.py
        - python forage.py -w csv
        - python forage.py -w json
        - jsonlint output-hydrometric.json
    - os: linux
      language: ruby
      rvm: "2.2"
      install: "bundle"
      script:
        - ruby forage.rb
        - ruby forage.rb -w csv
        - ruby forage.rb -w json
        - ruby forage.rb -w yaml
        - jsonlint output-hydrometric.json
        - csvlint output-hydrometric.csv
        - yamllint output-hydrometric.yaml
    - os: osx
      language: ruby
      rvm: "2.2"
      install: "bundle"
      script:
        - ruby forage.rb
        - ruby forage.rb -w csv
        - ruby forage.rb -w json
        - ruby forage.rb -w yaml
        - jsonlint output-hydrometric.json
        - csvlint output-hydrometric.csv
        - yamllint output-hydrometric.yaml
